# Use root/example as user/password credentials
version: '1'

services:

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: TripAdvisor_Locations
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_HOST: %

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


